# Generated by Django 2.1.3 on 2018-11-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0001_initial'),
        ('Courses', '0002_remove_course_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.ForeignKey(default=1, on_delete='CASCADE', related_name='courses', to='loginregister.College'),
            preserve_default=False,
        ),
    ]
