# Generated by Django 2.1.3 on 2018-11-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='equivalencies',
            field=models.ManyToManyField(related_name='_course_equivalencies_+', to='Courses.Course'),
        ),
    ]
