# Generated by Django 2.1.3 on 2018-11-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='student', max_length=20),
            preserve_default=False,
        ),
    ]
