# Generated by Django 2.1.3 on 2019-02-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0003_auto_20190201_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(related_name='users', through='loginregister.Permission', to='loginregister.Dept'),
        ),
    ]
