# Generated by Django 2.1.3 on 2019-02-05 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0004_auto_20190203_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accesslevel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
