# Generated by Django 2.1.3 on 2019-02-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0005_auto_20190204_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='levelname',
            field=models.CharField(default='Student', max_length=25),
            preserve_default=False,
        ),
    ]
